[package]
name = "puffin-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http-cache-reqwest = "0.11.3"
reqwest = { version = "0.11.22", features = ["json", "gzip", "stream"] }
reqwest-middleware = "0.2.3"
reqwest-retry = "0.3.0"
serde = "1.0.188"
serde_json = "1.0.107"
thiserror = { version = "1.0.49" }
url = { version = "2.4.1" }
