[package]
name = "puffin-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
puffin-requirements = { path = "../puffin-requirements" }

http-cache-reqwest = { version = "0.11.3" }
reqwest = { version = "0.11.22", features = ["json", "gzip", "brotli"] }
reqwest-middleware = { version = "0.2.3" }
reqwest-retry = { version = "0.3.0" }
serde = { version = "1.0.188" }
serde_json = { version = "1.0.107" }
thiserror = { version = "1.0.49" }
url = { version = "2.4.1" }
tracing = "0.1.37"
indicatif = "0.17.7"
